Assignments/images challenge
bhs-intro-to-programming/elijahsur pull request #4
Opened 2022-09-21 21:51 UTC by elijahsur

still working on this, got one of them done

2022-09-22 04:00 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  return "done!"
As I talked about today in class, when you're writing functions for their side effects (such as drawing on the screen) you don't really need to return anything. It doesn't really matter if you do but it's a bit distracting to someone reading the code who then has to think about why you're returning a value.

2022-09-22 04:16 UTC, elijahsur commented on assignments/images-challenge/code.js
> +    if (alt % 2 == 0);
could you explain what the ";" characters do? i keep seeing them in code, but i don't fully understand their use

2022-09-22 04:17 UTC, elijahsur commented on assignments/images-challenge/code.js
> +  return "done!"
i mainly just used "return "done!" to stop the "undefined" answer from the REPL from showing, but i understand how it could mess with the reading of the code

2022-09-22 04:18 UTC, elijahsur commented on assignments/images-challenge/code.js
> +  let x = 0;
i'll look over the slide in the meantime, since i don't really remember much of the "for" loop

2022-09-23 16:35 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  return "done!"
Ah, that's actually a pretty okay reason. Eventually you should take it out but if you're using it for debugging while you're developing, that's cool.

2022-09-23 17:46 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    if (alt % 2 == 0);
I think we talked about this a bit in class but basically they are used to delimit "statements". For now the kinds of statements you know about that should have a `;` at the end are assignments and returns. E.g.

```javascript
let x = 10;
return a;
y = 200;
```

An `if` statement is more complicated and technically has the form:

`if (`condition`)` 

followed by either a single statement (which will end with a `;`) or a block contained in `{}`

So either:

```javascript
if (whatever)
   return something;
```

Or

```javascript
if (whatever) {
  return something;
}
```

I'd *strongly* recommend *always* using `{}`s as doing so will prevent a whole bunch of common mistakes.

2022-09-27 00:26 UTC, gigamonkey requested changes
I think you can simplify this code a bit and address the comments I left.

2022-09-27 00:26 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +    drawFilledCircle(width / 2, height / 2, factor, color)
The first iteration of this loop it seems like this would draw a huge circle since `factor` starts out at `width + height`?

2022-09-27 00:26 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  let alternate = 250;
I'm a little confused what this variable is supposed to be. It starts at 250 and gets incremented by one but seems to be used only to detect whether you're on an odd or even circle. Feels redundant to me.

2022-09-27 00:35 UTC, elijahsur commented on assignments/images-challenge/code.js
> +    drawFilledCircle(width / 2, height / 2, factor, color)
i was playing around with that width+height, trying to figure out a good replacement for my previous method of just using "250". the width+height is not permanent

2022-09-27 00:37 UTC, elijahsur commented on assignments/images-challenge/code.js
> +  let alternate = 250;
i think i accidentally set "alternate" to 250 while trying to change the "factor" variable. it's meant to be at 0, which ill fix now

2022-11-04 21:56 UTC, elijahsur commented
done with this

2022-11-05 04:29 UTC, gigamonkey approved these changes
Sounds good. You can go ahead and merge this.

2022-11-05 22:15 UTC, elijahsur commented
cant seem to merge this, says it needs a review still

2022-11-05 22:15 UTC, merged