Assessments/unit 01
bhs-intro-to-programming/elijahsur pull request #5
Opened 2022-09-30 22:32 UTC by elijahsur

2022-10-04 00:14 UTC, gigamonkey requested changes
Marking this as request changes since you should still do the remaining problems. But this looks pretty good. Some comments about specifics below.

2022-10-04 00:14 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (oneword.length < twoword.length*2) {
This is really close. However you've made it too complicated and thus missed a case: if the first condition (`oneword.length > twoword.length * 2`) is not true you can just return false. But because you explicitly include the check you now miss the case where `oneword.length === twoword.length * 2`. As a consequence this function will return `undefined` in that case. Which arguably is close to correct because `undefined` counts as a "falsy" value in Javascript. But I'm pretty sure you weren't counting on that.

2022-10-04 00:14 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return whole.substring(whole.length / 2, whole.length)
This is correct. Note you can also use the one-argument version: `whole.substring(whole.length / 2)` since the second argument defaults to the length of the string if not provided.

2022-10-04 00:14 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return whole.substring(0, 1) + whole.substring(2, 3) + whole.substring(4, 5)
This is correct but maybe even easier would be to use `[]`: i.e. `whole[0] + whole[2] + whole[4]`.

2022-10-04 00:14 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  return whole.substring(whole.length - 1, whole.length).toUpperCase() + whole.substring(whole.length - 1, whole.length).toLowerCase()
Again correct but using both the two-arg version of `substring` and using `substring` instead of `[]` makes this a lot more code to read than the equivalent `whole[whole.length - 1].toUpperCase() + whole[whole.length - 1].toLowerCase()`.

And maybe even better would be to introduce a variable:

```javascript
const upDownLastCharacter = (whole) => {
  const last = whole[whole.length - 1];
  return last.toUpperCase() + last.toLowerCase();
};
```

2022-10-04 00:14 UTC, gigamonkey commented on assessments/unit-01/code.js
> +  if (number % 2 == 1) {
This one works because `== 0` and `== 1` are in fact all the possibilties. But the code would be even easier to read with an `if`/`else`:

```javacript
if (number % 2 === 0) {
  return 'yes';
} else {
  return 'no';
}
```

And even tidier, if you remember the `?:` operator from the pig latin assignment:

```javascript
return number % 2 === 0 ? 'yes" : 'no';
```

2022-10-04 17:19 UTC, elijahsur commented on assessments/unit-01/code.js
> +  return whole.substring(0, 1) + whole.substring(2, 3) + whole.substring(4, 5)
I just forgot the way to write [], so I kind of defaulted to using substrings

2022-11-04 22:02 UTC, elijahsur commented on assessments/unit-01/code.js
> +  if (oneword.length < twoword.length*2) {
hopefully fixed!

2022-11-04 22:06 UTC, elijahsur commented on assessments/unit-01/code.js
> +  return whole.substring(whole.length / 2, whole.length)
fixed

2022-11-04 22:10 UTC, elijahsur commented on assessments/unit-01/code.js
> +  return whole.substring(whole.length - 1, whole.length).toUpperCase() + whole.substring(whole.length - 1, whole.length).toLowerCase()
simplified!

2022-11-04 22:31 UTC, elijahsur commented on assessments/unit-01/code.js
> +  if (number % 2 == 1) {
simplified!

2022-11-04 22:31 UTC, merged