Assignments/array functions
bhs-intro-to-programming/elijahsur pull request #8
Opened 2022-10-17 21:51 UTC by elijahsur

haven't figured out pyramids yet, will work on it today

2022-10-19 02:52 UTC, gigamonkey requested changes
You're pyramid function isn't quite right; why don't you try again. I left you a hint.

2022-10-19 02:52 UTC, gigamonkey commented on assignments/array-functions/code.js
> +  if (count >= 1) {
This works but you can simplify any code of the form:

```javascript
if (condition) {
  return true;
} else {
  return false;
}
```

down to just:

```javascript
return condition;
```

2022-10-19 04:19 UTC, elijahsur commented on assignments/array-functions/code.js
> +  for (let i = 0; i < numbers; i++) {
I was having some trouble with the pyramid arrays, so I just tried to code a simple counting part first

I'll definitely try the nested loop tomorrow

2022-10-20 22:13 UTC, elijahsur commented on assignments/array-functions/code.js
> +  for (let i = 0; i < numbers; i++) {
Fixed the pyramid problem, still a little unintuitive to me

2022-10-20 22:16 UTC, elijahsur commented on assignments/array-functions/code.js
> +      count++;
simplified it!

2022-10-24 00:14 UTC, gigamonkey approved these changes
Looks good! You can go ahead and merge.

2022-10-24 00:14 UTC, gigamonkey commented on assignments/array-functions/code.js
> +  const pyramid = []
This technically works but it's probably a good idea to not get in the habit of naming local variables inside a function the same as the function itself. Later on we'll learn about "recursive" functions that call themselves. If you did this in one of them then you wouldn't be able to call the function from within itself because the local variable would be hiding (sometimes called "shadowing") the variable naming the function.

2022-10-24 00:50 UTC, merged